### ISSUE TITLE
Installing via SpoonInstall does not work

### ISSUE THREAD

**Issue by colinsullivan** [peterklijn/hammerspoon-shiftit#2] opened 2020-05-22 18:44 UTC
The error console just shows the entire GitHub HTML but maybe this is the relevant bit?

```
<meta name="selected-link" value="/peterklijn/hammerspoon-shiftit.git/raw/master/docs/docs.json" data-pjax-transient>
```

**Comment by peterklijn** [comment] 2020-05-25 10:21
Thanks for reporting @colinsullivan, I was able to reproduce the problem.

I believe it's fixed now, I've updated [the readme](https://github.com/peterklijn/hammerspoon-shiftit#spooninstall) with instructions.

Would you mind trying again? And if it doesn't work, would you mind sharing your `init.lua`?

**Comment by peterklijn** [comment] 2020-09-01 08:04
Closing due to no reply.

**Closed by peterklijn** 2020-09-01 08:04 UTC
